FROM node:16-alpine

EXPOSE 3000

RUN ["apk", "add", "--no-cache", "yarn", "git"]
WORKDIR /srv
RUN ["git", "clone", "https://github.com/MrPrimate/ddb-proxy", "." ]
RUN ["yarn", "install"]

CMD [ "node", "index.js" ]